#
# apt installs
#
- name: add keys to apt
  apt_key: url={{item}} state=present
  with_items: apt_keys

- name: add ppas to apt
  apt_repository: repo="{{item}}" update_cache=yes
  with_items: apt_ppas

- name: install apt packages
  apt: name={{item}} state=latest update_cache=yes
  with_items: apt_packages