# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# Modify as-needed!

- name: install npm modules
  npm: path="{{clone_path}}"

